spring:
  datasource:
    url: jdbc:postgresql://localhost:54332/monitoring-demo
    username: monitoring-demo
    password: monitoring-demo
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      leak-detection-threshold: 60000
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:sql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        type:
          preferred_instant_jdbc_type: timestamp
    open-in-view: false
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
logging:
  level:
    org.springframework: info
