apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monitoring-demo
  namespace: default
  labels:
    app: monitoring-demo
spec:
  replicas: 1
  serviceName: monitoring-demo
  selector:
    matchLabels:
      app: monitoring-demo
  template:
    metadata:
      labels:
        app: monitoring-demo
    spec:
      imagePullSecrets:
      - name: nexus-registry-credentials
      containers:
      - name: monitoring-demo
        image: nexus.esolutions.ro/mstaicu/monitoring-demo
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
        - name: http
          containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 10" ]  #set prestop hook
        resources:
          requests:
            cpu: 100m
            memory: 600Mi
          limits:
            memory: 600Mi
        livenessProbe:
          httpGet:
            port: http
            path: /actuator/health/liveness
          failureThreshold: 3
        readinessProbe:
          httpGet:
            port: http
            path: /actuator/health/readiness
          periodSeconds: 60
          failureThreshold: 1
        startupProbe:
          httpGet:
            port: http
            path: /actuator/health/readiness
          failureThreshold: 100
          periodSeconds: 1
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=60.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/dumps -XX:+UseG1GC -XX:+UseStringDeduplication -Duser.timezone=Europe/Bucharest -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom"
        - name: SPRING_SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              key: username
              name: monitoring-demo-credentials
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: monitoring-demo-credentials
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://monitoring-demo-db.infrastructure.svc.cluster.local:5432/monitoring-demo"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: monitoring-demo-credentials
              key: datasource.username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: monitoring-demo-credentials
              key: datasource.password
        - name: APP_ENV
          value: 'local'
        volumeMounts:
        - name: heap-dumps
          mountPath: /dumps
      volumes:
      - name: heap-dumps
        emptyDir: { }

